version: "2.0"
services:
    rabbit1:
        image: rabbitmq:3-management
        hostname: rabbit1
        ports:
            - 5672:5672 #集群内部访问的端口
            - 15672:15672 #外部访问的端口
        environment:
            - RABBITMQ_DEFAULT_USER=guest #用户名
            - RABBITMQ_DEFAULT_PASS=guest #密码
            - RABBITMQ_ERLANG_COOKIE='rabbitmq'
    rabbit2:
        image: rabbitmq:3-management
        hostname: rabbit2
        ports:
            - 5673:5672 #集群内部访问的端口
        environment:
            - RABBITMQ_ERLANG_COOKIE='rabbitmq'
        links:
            - rabbit1
    rabbit3:
        image: rabbitmq:3-management
        hostname: rabbit3
        ports:
            - 5674:5672 #集群内部访问的端口
        environment:
            - RABBITMQ_ERLANG_COOKIE='rabbitmq'
        links:
            - rabbit1
            - rabbit2
